version: '3'

services:
  scrapy:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile

    #this command keeps the container open
    command: tail -F anything 
    
    volumes:
      - ./Data:/app/Data

    ports:
      - 27017:27017


